using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

[Serializable]
public class DialogContainer : ScriptableObject
{
    [Header("Generated by graph")]
    public List<NodeLinkData> NodeLinks = new List<NodeLinkData>();
    public List<NodeData> NodeData = new List<NodeData>();
    public List<ExposedProperty> ExposedProperties = new List<ExposedProperty>();
    public DialogPosition Position;

    public NodeData FindNode(string targetNodeGuid)
    {
        List<NodeData> results = NodeData.Where(x => x.Guid == targetNodeGuid).ToList();
        if(results.Count == 0)
        {
            Debug.LogError("Could not find target node");
            throw new Exception();
        }
        else
        {
            return results[0];
        }
    }

    public List<NodeLinkData> FindNextLinksForNode(NodeData node)
    {
        return NodeLinks.Where(x => x.BaseNodeGuid == node.Guid).ToList();
    }
}

public enum DialogPosition
{
    Top,
    Right,
    Bottom,
    Left,
    Center
}